# Generated by Django 3.1.1 on 2020-09-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='slug',
            field=models.CharField(default='slug', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schema',
            name='slug',
            field=models.CharField(default='slug', max_length=100),
            preserve_default=False,
        ),
    ]
