# Generated by Django 3.1.1 on 2020-09-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0002_auto_20200923_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatypes',
            name='range_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datatypes',
            name='range_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
