# Generated by Django 3.1.1 on 2020-09-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0003_auto_20200923_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='slug',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
