# Generated by Django 3.1.1 on 2020-09-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0005_auto_20200923_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datatypes',
            name='range_max',
        ),
        migrations.RemoveField(
            model_name='datatypes',
            name='range_min',
        ),
        migrations.AddField(
            model_name='column',
            name='range_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='column',
            name='range_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
