# Generated by Django 3.1.1 on 2020-09-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0007_dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='url',
            field=models.FilePathField(blank=True, null=True, path='media/datasets'),
        ),
    ]
