# Generated by Django 3.1.1 on 2020-09-29 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0011_auto_20200929_0953'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='column',
            unique_together={('schema', 'order')},
        ),
    ]
