# Generated by Django 3.1.1 on 2020-09-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0012_auto_20200929_0957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='column',
            name='range_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='column',
            name='range_min',
            field=models.IntegerField(default=0),
        ),
    ]
